/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MessageService } from "../message.service";
import { MessageCreateInput } from "./MessageCreateInput";
import { MessageWhereInput } from "./MessageWhereInput";
import { MessageWhereUniqueInput } from "./MessageWhereUniqueInput";
import { MessageFindManyArgs } from "./MessageFindManyArgs";
import { MessageUpdateInput } from "./MessageUpdateInput";
import { Message } from "./Message";

export class MessageControllerBase {
  constructor(protected readonly service: MessageService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Message })
  async create(@common.Body() data: MessageCreateInput): Promise<Message> {
    return await this.service.create({
      data: {
        ...data,

        chatId: {
          connect: data.chatId,
        },

        message: {
          connect: data.message,
        },
      },
      select: {
        agentIdtype: true,

        chatId: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        isPoll: true,

        message: {
          select: {
            id: true,
          },
        },

        options: true,
        quesions: true,
        updatedAt: true,
        userId: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Message] })
  @ApiNestedQuery(MessageFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Message[]> {
    const args = plainToClass(MessageFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        agentIdtype: true,

        chatId: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        isPoll: true,

        message: {
          select: {
            id: true,
          },
        },

        options: true,
        quesions: true,
        updatedAt: true,
        userId: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Message })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async findOne(
    @common.Param() params: MessageWhereUniqueInput
  ): Promise<Message | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        agentIdtype: true,

        chatId: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        isPoll: true,

        message: {
          select: {
            id: true,
          },
        },

        options: true,
        quesions: true,
        updatedAt: true,
        userId: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Message })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async update(
    @common.Param() params: MessageWhereUniqueInput,
    @common.Body() data: MessageUpdateInput
  ): Promise<Message | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          chatId: {
            connect: data.chatId,
          },

          message: {
            connect: data.message,
          },
        },
        select: {
          agentIdtype: true,

          chatId: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          isPoll: true,

          message: {
            select: {
              id: true,
            },
          },

          options: true,
          quesions: true,
          updatedAt: true,
          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Message })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async delete(
    @common.Param() params: MessageWhereUniqueInput
  ): Promise<Message | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          agentIdtype: true,

          chatId: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          isPoll: true,

          message: {
            select: {
              id: true,
            },
          },

          options: true,
          quesions: true,
          updatedAt: true,
          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/messages")
  @ApiNestedQuery(MessageFindManyArgs)
  async findManyMessages(
    @common.Req() request: Request,
    @common.Param() params: MessageWhereUniqueInput
  ): Promise<Message[]> {
    const query = plainToClass(MessageFindManyArgs, request.query);
    const results = await this.service.findMessages(params.id, {
      ...query,
      select: {
        agentIdtype: true,

        chatId: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        isPoll: true,

        message: {
          select: {
            id: true,
          },
        },

        options: true,
        quesions: true,
        updatedAt: true,
        userId: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/messages")
  async connectMessages(
    @common.Param() params: MessageWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      messages: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/messages")
  async updateMessages(
    @common.Param() params: MessageWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      messages: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/messages")
  async disconnectMessages(
    @common.Param() params: MessageWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      messages: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
