/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  ValidateNested,
  IsBoolean,
} from "class-validator";
import { ChatWhereUniqueInput } from "../../chat/base/ChatWhereUniqueInput";
import { Type } from "class-transformer";
import { MessageWhereUniqueInput } from "./MessageWhereUniqueInput";
import { MessageCreateNestedManyWithoutMessagesInput } from "./MessageCreateNestedManyWithoutMessagesInput";
import { IsJSONValue } from "@app/custom-validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class MessageCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  agentIdtype?: string | null;

  @ApiProperty({
    required: true,
    type: () => ChatWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ChatWhereUniqueInput)
  @Field(() => ChatWhereUniqueInput)
  chatId!: ChatWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isPoll?: boolean | null;

  @ApiProperty({
    required: true,
    type: () => MessageWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => MessageWhereUniqueInput)
  @Field(() => MessageWhereUniqueInput)
  message!: MessageWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => MessageCreateNestedManyWithoutMessagesInput,
  })
  @ValidateNested()
  @Type(() => MessageCreateNestedManyWithoutMessagesInput)
  @IsOptional()
  @Field(() => MessageCreateNestedManyWithoutMessagesInput, {
    nullable: true,
  })
  messages?: MessageCreateNestedManyWithoutMessagesInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  options?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  quesions?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  userId?: string | null;
}

export { MessageCreateInput as MessageCreateInput };
